org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.configuration-cache=true

minecraft_version=1.21.1
neoforge_version=21.1.233
create_version=6.0.10-280
ponder_version=1.0.82
flywheel_version=1.0.6
registrate_version=MC1.21-1.3.0+67
opencomputers_version=1.9.4-2
scalablecatsforce_version=3.3.3-build-15

mod_id=opencomputersservo
mod_name=OpenComputers Servo
mod_version=0.1.0
mod_group_id=dev.buzzec.opencomputersservo
mod_authors=Buzzec
mod_description=Computer-controlled servo motors connecting OpenComputers and Create rotation.
